# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55bc13a74c7c7ff7f849353a627c3befcf52817ce36f8c10dbd12866200d46b68c55a42678374099eb84c965b799d7c6a1223a74e3f8d9a0a2332fb5855f6902

test:
  secret_key_base: 922a714e31c80c815414d89074bee25f069c5dea95aa6d950c944a2fa3fe0fb6fd2c3b7c043abb8a52563f028f485b2b42851487f0481cf2affd7f471180a772

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
